#!/bin/zsh


## get the cursor position
 # => line column

function terminal:cursor:get:position {
  tput u7 >&3
  IFS='[;' read -u 3 -srd R -A CurPos
  echo ${CurPos[2,-1]}            
} 

# examples
~% terminal:cursor:get:position
 # 24 1
~% CURPOS=( $(terminal:cursor:get:position) ) 
~% echo $CURPOS[1]                           
 # 26
~% echo $CURPOS[1]
 # 26
~% function testCurPos {                     
  local CurPos=( $(terminal:cursor:get:position) )
  echo $CurPos[1]
}
~% testCurPos                  
 # 6
~% testCurPos                  
 # 8
~% testCurPos; testCurPos      
 # 10
 # 11
~% function testCurPosNoNewLine {
~%   local CurPos=( $(terminal:cursor:get:position) )
~%   echo -n $CurPos[1]
~% }
~% testCurPosNoNewLine; testCurPosNoNewLine; echo
 # 1717

